//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visits
    {
        public int VS_ID { get; set; }
        public int VS_ID_ANIMALS { get; set; }
        public int VS_ID_WATERFALLS { get; set; }
        public Nullable<System.DateTime> VS_DATE { get; set; }
        public string VS_DESCRIPTION { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual Waterfalls Waterfalls { get; set; }
    }
}
