//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waterfalls
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Waterfalls()
        {
            this.Visits = new HashSet<Visits>();
        }
    
        public int WF_ID { get; set; }
        public string WF_NAME { get; set; }
        public Nullable<int> WF_HEIGHT { get; set; }
        public byte[] WF__PHOTO { get; set; }
        public int WF_RIVER_ID { get; set; }
        public int WF_TYPE_ID { get; set; }
    
        public virtual Rivers Rivers { get; set; }
        public virtual Types Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visits> Visits { get; set; }
    }
}
